### ISSUE TITLE
Problem Capturing Exception from Google Ads API Auth

### ISSUE THREAD

**Issue by mwebber92** [googleapis/google-auth-library-php#275]
Hi all
I'm having problem. i can't catch exception to log it.

i have a class with this initialization:

```php
$oauth2 = (new OAuth2TokenBuilder())
            ->withClientId($this->container->getParameter('oauth2.google.adwords.clientId'))
            ->withClientSecret($this->container->getParameter('oauth2.google.adwords.clientSecret'))
            ->withRefreshToken($this->accountOAuth2Connection->getRefreshToken())
            ->build();

$this->oauth2 = $oauth2;
```
later i have this:
```php
try {
            $this->oauth2->fetchAuthToken();
            $oauthConnection = true;
} catch ( Exception $e) {
            Logger::get()->error($e->getMessage());
            Logger::get()->error($e->getTraceAsString());
} catch (\Exception  $e) {
            echo $e->getMessage();
} catch(RequestException $e) {
          print_r($e->getResponse()->json()); //Get error response body
}
```
but no matter what catch condition i add i always get this (for expired google tokens):

```
18:36:41 ERROR     [app] Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}


18:36:41 ERROR     [app] #0 /var/www/clients/client0/web2/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/clients/client0/web2/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/clients/client0/web2/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/clients/client0/web2/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/clients/client0/web2/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/clients/client0/web2/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/clients/client0/web2/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/clients/client0/web2/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/clients/client0/web2/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/clients/client0/web2/vendor/guzzlehttp/guzzle/src/Client.php(130): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/clients/client0/web2/vendor/google/auth/src/HttpHandler/Guzzle6HttpHandler.php(34): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/www/clients/client0/web2/vendor/google/auth/src/OAuth2.php(502): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
#12 /var/www/clients/client0/web2/vendor/google/auth/src/Credentials/UserRefreshCredentials.php(119): Google\Auth\OAuth2->fetchAuthToken(Object(Google\Auth\HttpHandler\Guzzle6HttpHandler))
#13 /var/www/clients/client0/web2/src/BaseBundle/Util/Service/Google/Adwords/GoogleAdwordsReport.php(88): Google\Auth\Credentials\UserRefreshCredentials->fetchAuthToken()
#14 /var/www/clients/client0/web2/src/MonitoringManagerBundle/Handler/Connection/GoogleAdwordsCheck.php(56): BaseBundle\Util\Service\Google\Adwords\GoogleAdwordsReport->checkConnection()
```

Is there a way to capture this? 
\Exception or any other i found in the code doesn't work and ignores it.
Could it be because it uses guzzlehttp? i readed that there is some setting http_errors in code as setting for guzzle, but didnt found place to pass it as parameter

Thanks!

  - OS: Ubuntu
  - PHP version: 7.2
  - Package version: 44.0.0

**Comment by danoscarmike** [comment]
Possibly related to #274

**Comment by bshaffer** [comment]
Your error is from the OAuth API, and the error indicates that the refresh token you're supplying is invalid (see [this issue](https://github.com/googleapis/signet/issues/123) for reference).

You already are receiving the full response from the API and the stack trace, so I am not sure what you are hoping to receive with `http_errors`, but there is a way to modify your guzzle HTTP client. The `fetchAuthToken` method takes an optional HTTP Handler. To use it, do something like this:

```php
// Your custom configured Guzzle HTTP Client
$http = new GuzzleHttp\Client([
    'http_errors' => true,
]);
$httpHandler = Google\Auth\HttpHandler\HttpHandlerFactory::build($http);
$oauth2->fetchAuthToken($httpHandler);
```

If you want to see the raw HTTP request/response going across the wire. You can do that like this while using a local proxy such as Charles:

```php
// for debugging only. NEVER use this to production!
$http = new GuzzleHttp\Client([
    'verify' => false,
    'proxy' => 'localhost:8080'
]);
```
